# Generated by Django 3.1.4 on 2021-01-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='detail',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
