# Generated by Django 3.1.4 on 2021-01-20 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_userprofile_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
