# Generated by Django 3.1.4 on 2021-01-25 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userprofile_is_first_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationcustomlistoption',
            name='item_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='item_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usercustomlistoption',
            name='item_name',
            field=models.CharField(max_length=100),
        ),
    ]
