# Generated by Django 3.1.4 on 2021-01-26 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_shoppinglistitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustomlistoption',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
