# Generated by Django 3.1.4 on 2021-01-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_usercustomlistoption_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglistitem',
            name='price',
        ),
        migrations.AddField(
            model_name='organisationcustomlistoption',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
